# Generated by Django 5.2.8 on 2025-11-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="todo",
            old_name="created_add",
            new_name="created_at",
        ),
    ]
