# Generated by Django 5.2.8 on 2025-11-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_created_add_todo_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "🆕 Yangi"),
                    ("in_progress", "⏳ Jarayonda"),
                    ("done", "✅ Bajarilgan"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
