# Generated by Django 5.2.8 on 2025-11-16 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_todo_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="status",
            field=models.CharField(
                choices=[
                    ("new", "🟢 Yangi"),
                    ("in_progress", "⏳ Jarayonda"),
                    ("done", "✅ Bajarilgan"),
                ],
                default="new",
                max_length=50,
            ),
        ),
    ]
